/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in full app setups. It is checked in here so
// Phase 0 typecheck works before the first local Next.js run.
